camera_type: "kinect_2"
full_path: "/home/mukhtar/git/static_object_position_tracking/models/"
path_original_pcd: "/home/mukhtar/git/static_object_position_tracking/src/"
path_filtered_pcd: "/home/mukhtar/git/static_object_position_tracking/src/"
segm_limits: {x: {min: 0.1, max: 0.6}, y: {min: -0.6, max: 0.6}, z: {min: 0.0, max: 0.2}} ## normal table