camera_type: "kinect_1"
full_path: "/home/ghanim/git/static_object_position_tracking/models/"
path_original_pcd: "/home/ghanim/git/static_object_position_tracking/src/"
path_filtered_pcd: "/home/ghanim/git/static_object_position_tracking/src/"